{% set name = "ansimarkup" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 96c65d75bbed07d3dcbda8dbede8c2252c984f90d0ca07434b88a6bbf345fad3

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - colorama
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - ansimarkup

about:
  home: https://github.com/gvalkov/python-ansimarkup
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Produce colored terminal text with an xml-like markup

extra:
  recipe-maintainers:
    - mariusvniekerk
