{% set name = "ansimarkup" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ffd040e822e6d329d42d250179bd3d9a9c9f6ed6936a30d17b5f7d56a8f03ef0

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - colorama
    - python

test:
  imports:
    - ansimarkup

about:
  home: https://github.com/gvalkov/python-ansimarkup
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Produce colored terminal text with an xml-like markup

extra:
  recipe-maintainers:
    - mariusvniekerk
