{% set name = "ansimarkup" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b3e3d93fecc5b64d23a6e8eb96dbc8b0b576a211829d948afb397d241a8c51b

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - colorama
    - python

test:
  imports:
    - ansimarkup

about:
  home: https://github.com/gvalkov/python-ansimarkup
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Produce colored terminal text with an xml-like markup

extra:
  recipe-maintainers:
    - mariusvniekerk
