travis:
  secure:
    BINSTAR_TOKEN: vZU93tljzvMaWkLEo0VfF7U/o4oHdSlNfCaOEnHpB3aDX+LdPXMujRaQjrhvOiI+dfJr0Mi5Xy9+RfzOX5y8A7Vpz5PxK63cclUH7bRl50keulGdGednIyZ99mRP7JCEo9+eLoP+LZ6NRq4ztkLeKmo+wjwLBjXnJLI/zabv8Fd63L0nSRM6QMgcHMcuUtSP1r53q7MJORAbZgeJa36NQgZ05jplt77tcq02umKAJgXB6kud/NJEMTmrvYLHmnXbq1CZRl4cFspydaTHt36VCQOnAL2YY9Oo3Q44mtTHDAQnO0NeBeQS47mf2lA1VieJhR/LvVFDxWJacg2m8lzUuJEYf03viJaBJCVBmnjXzuidxzunceUKi5ubkBZmxga/Ypkpc2JBt2igTm+NoUJnbcl3yWLOEXuPqmEU5c5ZsIZhW4a1Ci9ti+lrABsc3HXIEAjLCL5lLOGpDDBOpd8opENqqkI26dF6fEL6v/ShVUh+eN5ckZe5p1JUQuer0Hb772HBD3kFHfCe3jRZ4RMAcewmNm6Tsb6kZF4uOXnRlwMi6qrNmrjvR7oswDZMWGEiS6oklWMnHj5AU+LxA1utgbZ6UHnYjxWMOdt31+1VhhohHcVKrvb/h1uQwQLYxWbwzpFj3gndYwdm+SmZ/wHg/RAyPKOSt5Ee3+ujyCHkh7Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
