travis:
  secure:
    BINSTAR_TOKEN: DPMzElahjVEtnZAUNBPjqUsK/TZmzAYnVqTyp2Bt+7/ef+t6nba/22NgkQpZVFKrSNkh4jOCBY6TymEt+Rdpl0HJKV2jjmQDcidxH2pKfLvbGmDD2EsyqT0u8+nRK7DwdDfZkVKTjGfigvU7DfnxvCK9FiZd9IxxKl9+/Vg5wXVTpR3ifIt7GdHen4WWpuvHf3oHa8TV5xh7mVS+MC1sop2l/Yc1frIgUc+qTqgzdKMNtHAd7Ouptyg4hHcDXHIgdv7Ris5wvpnNC+F2EjLfCL5gJ021MkmMm6DW6DHIyQAYO0ACU465xzHQmXATrKgZdjwzAaD028Okpgms69o2/M2FQ2au2cc+B9n4npKnaoRtBk0T2vPgndCTAa+AOn+x/UEjEwzWUhc0S96U0xVafN+nvXCm9Tpy8HEK+7HznJsExtvj0PIGdbyL9agUqKdirzRNZnjIl7F6rf0h8j07DGPlCLfILhszohWLi0/sIW/+zrVg2mJoOJKevbLw+deK2RjCl7zashSfsIxi6TYEkaUr42VAN8QMvr1cwG00lrBRAPKWer388MNW7v0l/AD0BbjnE1G6ZyqncTtLkYDrbm2o8gACPPALQmbxLk5umLOFqi/6UCMx2vsJXeSocLaHYbecK4zt7fSDFnntEwfQQoUnDyL3nlP8UhyVHVGujkc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
